#将这个配置添加到nacos上
#spring:
#  cloud:
#    loadbalancer:
#      retry:
#        enabled: true # 重试机制开关
#    #向sentinel控制台注册服务
#    sentinel:
#      filter:
#        #打开/关闭掉对Spring MVC端点的保护
#        enabled: true
#      transport:
#        dashboard: 127.0.0.1:8719
#      #取消控制台懒加载
#      eager: true
#  mvc:
#    servlet:
#      load-on-startup: 100
#
## feign
#feign:
#  sentinel:
#    enabled: true # 不设置这个Feign的断路无效
#
##添加sentinel依赖后 暴露/actuator/sentinel端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
